package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestStringTo2DArray_ProducesCorrect2DNumArray(test *testing.T) {
	input := `..S..
..^..
.^.^.
.....`

	output := StringTo2DArray(input)

	assert.Equal(test, 4, len(output), "Expected: 4, Received: %s", len(output))
	assert.Equal(test, ".", output[0][1], "Expected: '.', Received: %s", output[0][1])
	assert.Equal(test, "S", output[0][2], "Expected: 'S', Received: %s", output[0][2])
	assert.Equal(test, "^", output[2][3], "Expected: '^', Received: %s", output[2][3])
	assert.Equal(test, ".", output[3][4], "Expected: '.', Received: %s", output[3][4])

	input = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

	output = StringTo2DArray(input)

	assert.Equal(test, 16, len(output), "Expected: 16, Received: %s", len(output))
	assert.Equal(test, ".", output[0][6], "Expected: '.', Received: %s", output[0][6])
	assert.Equal(test, "S", output[0][7], "Expected: 'S', Received: %s", output[0][7])
	assert.Equal(test, "^", output[2][7], "Expected: '^', Received: %s", output[2][7])
	assert.Equal(test, ".", output[7][6], "Expected: '.', Received: %s", output[7][6])
	assert.Equal(test, "^", output[10][11], "Expected: '^', Received: %s", output[10][11])
}

func TestFindStartingBeam_ReturnsStartColIntForSBeam(test *testing.T) {
	input := StringTo2DArray(`..S..
..^..
.^.^.
.....`)

	output := FindStartingBeam(input)

	assert.Equal(test, 2, output, "Expected: 2, Received: %s", output)

	input = StringTo2DArray(`.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`)

	output = FindStartingBeam(input)

	assert.Equal(test, 7, output, "Expected: 2, Received: %s", output)
}

func TestCountTotalSplits_ReturnsTotalCountForSplitsComplete(test *testing.T) {
	input := StringTo2DArray(`..S..
..^..
.^.^.
.....`)

	output := CountTotalSplits(input)

	assert.Equal(test, 3, output, "Expected: 3, Received: %s", output)

	input = StringTo2DArray(`.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`)

	output = CountTotalSplits(input)

	assert.Equal(test, 21, output, "Expected: 21, Received: %s", output)
}

func TestPart1_ReturnsTotal(test *testing.T) {
	input := `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

	output := Part1(input)

	assert.Equal(test, 21, output, "Expected: 21, Received: %s", output)

	rawInput, _ := readFileToString("input.txt")

	output = Part1(rawInput)

	assert.Equal(test, 1585, output, "Expected: 1585, Received: %s", output)
}